# Generated by Django 2.1.7 on 2019-04-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='预约人')),
                ('phone', models.CharField(max_length=15, verbose_name='电话号码')),
                ('type', models.CharField(max_length=10, verbose_name='房屋类型')),
                ('describe', models.TextField(verbose_name='房屋描述')),
                ('address', models.CharField(max_length=10, verbose_name='预约地点')),
                ('village', models.CharField(max_length=10, verbose_name='小区名')),
                ('time', models.CharField(max_length=20, verbose_name='预约时间')),
                ('person', models.CharField(max_length=10, verbose_name='委托人')),
                ('entrust', models.CharField(max_length=10, verbose_name='委托类型')),
                ('status', models.CharField(max_length=10, verbose_name='处理状态')),
            ],
            options={
                'verbose_name': '委托记录',
                'verbose_name_plural': '委托记录',
                'db_table': 'entrust',
            },
        ),
    ]
